Mobile portfolio
omarbabou/my-portfolio pull request #1
Opened 2022-04-25 19:17 UTC by omarbabou

In this PR, I have achieved many things such as: 

    - Implemented #mobile portfolio skeleton version
    - Acquiring knowledge of flexbox    
    - Run tests using linters commands ex: **npx hint .** 
    - Make good message commits by following Gitflow instructions
    - Fix linters error

2022-04-25 20:08 UTC, ShahierNashaat requested changes
Hi @omarbabou , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-25 20:08 UTC, ShahierNashaat commented on index.html
> +      <div class="subcontent">
- [x] Please put the content in the `main` tag and the subcontinent in a `section` to make your HTML more semantic.
- [x] Also be noticed that you have to add a display:grid to your content because you will have other subcontinents in the future that will need to be organized.

2022-04-25 20:08 UTC, ShahierNashaat commented on index.html
> +      </div>
- [x] The Works section that will have the recent projects that you have made is missing please add it.
- [x] Also the About myself section that will have a brief about you and the technologies, languages, and the frameworks that you know also has to be inside it.
- [x] Also each one of them should be wrapped in a `section` tag.

2022-04-25 21:11 UTC, nicupop729 requested changes
Hi @omarbabou, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

## Highlights
 - [X] Correct GitHub flow practice :heavy_check_mark:
 - [X] Professional README :heavy_check_mark:
 - [X] Linters are passing :heavy_check_mark:
 - [X] Clean codebase :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-25 21:11 UTC, nicupop729 commented on index.html
> +        <a href="#" class="logo">My logo</a>
- [x] In order to respect the HTML semantics, kindly, take out the logo from the `nav`. Please take care to still keep it inside the `header` tag.

The logo is not part of navigation, hence its place would be outside of the mentioned container;

2022-04-25 21:11 UTC, nicupop729 commented on style.css
> +}
As you need to take the logo, outside of the `nav` tag (but still keep it in the `header`), you can use Flexbox on the `header` now;

- [x] Kindly, style the `header` with the use of Flexbox;

2022-04-25 21:11 UTC, nicupop729 commented on index.html
> +    <section class="content">
[optional]

I noticed you have 2 wrappers ('content' and 'subcontent').
 You can consider removing one.

Please take into consideration that the next step is to build the work cards. Those will have to be in a completely separate `section` container. If you consider building the next milestone as a 'subcontent' class, kindly, replace the `section` tag with `main` and the 'subontent' `div` with a `section` tag.

2022-04-25 21:11 UTC, nicupop729 commented on index.html
> +          I'm Idrissa Omar <br />
[OPTIONAL]

- [ ] Please take into consideration keeping only one name in your title as it makes your design not look very well on a small device; Also, I recommend this in order to respect the Figma design

Your design:
![image](https://user-images.githubusercontent.com/83596135/165175490-91a78e2a-2734-4aee-a1a6-b1da486623e8.png)

2022-04-25 21:17 UTC, nicupop729 commented on index.html
> +      <div class="subcontent">
**As you asked for a review for this milestone from the wrong link, kindly, ignore the above comment!**

2022-04-25 21:17 UTC, nicupop729 commented on index.html
> +      </div>
**As you asked for a review for this milestone from the wrong link, kindly, ignore the above comment!**

2022-04-26 10:47 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi @omarbabou,

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![thumbs-up-agree](https://user-images.githubusercontent.com/68796232/158491866-20000001-88c2-4735-bb47-1ff65c7a44db.gif)


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-26 14:35 UTC, merged