Contact form
omarbabou/my-portfolio pull request #5
Opened 2022-05-12 11:49 UTC by engrabdullahriaz

In this PR, I implemented the following steps:

    1. I learned how to validate the form.
    2. Write a good readme file for a good understanding of the project by the user.
    3. Understanding the importance of the User Experience.

2022-05-12 12:08 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi Team,

Nice job, you are almost there.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [x] Next time please implement all your change inside the branch you making the pull request with so the reviewer can make a proper review with inline comments.

- [ ] For the contact form please add the correct margin top for your section header and add the top left curvature and try to stick as much as possible to the given Figma design.

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/168070905-4219b18c-6c7a-4180-9431-419f28ed4c08.png)  | ![image](https://user-images.githubusercontent.com/68796232/168070870-fd91a745-8cc6-43bc-87fe-0c03f9b4adc2.png) |

- [ ] Kindly add hover and active (pressed) button interactions style to match the Figma design.

![image](https://user-images.githubusercontent.com/68796232/168071293-4a61f3d7-645e-4e91-b54d-3ace24930ed3.png)

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-12 15:43 UTC, arslanbisharat requested changes
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-05-12 15:43 UTC, arslanbisharat commented on README.md
- [ ] [OPTIONAL] Please add a proper live link to your readme.

2022-05-12 15:43 UTC, arslanbisharat commented on index.html
>        <section class="contact-me">
- [ ] As mentioned by the previous reviewer, please make the changes so your design looks like Figma's design. Your design looks like this right now. 

![image](https://user-images.githubusercontent.com/58504655/168115016-5eb1cfc8-6e25-4533-a172-bbac102d2a73.png)

2022-05-13 07:33 UTC, prolajumokeoni approved these changes
Hi @Team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Github flow was used correctly 🚀 
- Good design 💯  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Check inline comments_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-13 07:33 UTC, prolajumokeoni commented on index.html
>            If you have an application you are interested in developing, a feature
### OPTIONAL

Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![Screenshot_181](https://user-images.githubusercontent.com/69638013/168232983-da16558b-93b0-4734-aa88-929e25c4b5cc.png)  | ![Screenshot_180](https://user-images.githubusercontent.com/69638013/168232950-4b178cc5-46e1-4812-b4ca-51b092fcca6d.png)

- [ ] Good job making all the requested changes 👍🏿  Kindly increase the with of the paragraph text to have the same width as the form
- [ ] Please change the  color for name and email inputs to the color used in the Figma design 👍🏿

2022-05-13 10:19 UTC, merged